language: cpp

sudo: required

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - bazel

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libelf-dev libssl-dev libcap-dev linux-tools-`uname -r` linux-cloud-tools-`uname -r`
  - git submodule update --init --recursive

install:
  # install gcc-4.8 with c++11 support: https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90

compiler:
  - clang
  - gcc

script:
  - bazel build //src:all //src/quipper:all
  - bazel test //src:all //src/quipper:all
  - make perf_to_profile check clean -C src/
  - make quipper perf_converter check clean -C src/quipper/ -f Makefile.external
