package(
    default_visibility = [
        "//src:__subpackages__",
    ],
)

licenses(["notice"])

cc_library(
    name = "test_compat",
    testonly = 1,
    hdrs = [
        "test_compat.h",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
