# Description:
#   Test files for converting sampledb proto to profile proto.
licenses(["notice"])  # BSD

exports_files(
    [
        "LICENSE",
        "perf-overlapping-kernel-mapping.pb_proto",
        "single-event-single-process.perf.data",
        "single-event-multi-process.perf.data",
        "multi-event-single-process.perf.data",
        "multi-event-single-process.perf_data.pb.data",
        "with-callchain.perf.data",
    ],
)
